"use client";
import { useState, useTransition } from "react";
import { AppIcon } from "@/components/app-icon";
import { identitySchema, type Answers, type Identity, type SurveyInput } from "@/lib/surveys";
import { submitSurvey } from "@/app/s/[token]/actions";

export function PublicSurvey({ survey, token }: { survey: SurveyInput; token: string }) {
  const [step, setStep] = useState<"identity" | "questions" | "done">("identity");
  const [identity, setIdentity] = useState<Identity>({ full_name: "", phone: "", email: "" });
  const [answers, setAnswers] = useState<Answers>({}); const [error, setError] = useState("");
  const [submission] = useState(() => crypto.randomUUID()); const [website, setWebsite] = useState("");
  const [pending, startTransition] = useTransition();
  const answered = survey.questions.filter((q) => { const a = answers[q.id]; return Array.isArray(a) ? !!a.length : typeof a === "number" || (typeof a === "string" && !!a.trim()); }).length;
  const setAnswer = (id: string, value: Answers[string]) => setAnswers((old) => ({ ...old, [id]: value }));
  if (step === "done") return <section className="survey-public-card survey-thanks" role="status"><span className="survey-success-icon"><AppIcon name="checkCircle" size={52}/></span><p className="eyebrow">ĐÃ GỬI THÀNH CÔNG</p><h1>Cảm ơn bạn đã chia sẻ!</h1><p>Phản hồi của bạn đã được lưu lại. Mỗi ý kiến đều giúp công ty hiểu và cải thiện tốt hơn.</p><p className="muted">Bạn có thể đóng trang này.</p></section>;
  return <><header className="survey-public-heading"><p className="eyebrow">KHẢO SÁT NHÂN VIÊN</p><h1>{survey.title}</h1><p className="survey-description">{survey.description || "Hãy chia sẻ ý kiến của bạn để cùng xây dựng môi trường làm việc tốt hơn."}</p><span className="survey-public-meta">{survey.questions.length} câu hỏi · Không cần đăng nhập</span></header>
    {step === "identity" ? <form className="survey-public-card" onSubmit={(e) => { e.preventDefault(); const parsed = identitySchema.safeParse(identity); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } setIdentity(parsed.data); setError(""); setStep("questions"); window.scrollTo({ top: 0, behavior: "instant" }); }}><span className="survey-step">01</span><h2>Trước khi bắt đầu</h2><p className="muted">Cho chúng tôi biết bạn là ai. Chỉ cần họ tên và một thông tin liên hệ.</p><label>Họ và tên <span>*</span><input autoComplete="name" required maxLength={120} value={identity.full_name} onChange={(e) => setIdentity({ ...identity, full_name: e.target.value })} placeholder="Nhập họ tên của bạn"/></label><div className="survey-contact-grid"><label>Số điện thoại<input type="tel" autoComplete="tel" inputMode="tel" maxLength={16} value={identity.phone} onChange={(e) => setIdentity({ ...identity, phone: e.target.value })} placeholder="Ví dụ: 0901234567"/></label><label>Email<input type="email" autoComplete="email" maxLength={254} value={identity.email} onChange={(e) => setIdentity({ ...identity, email: e.target.value })} placeholder="ban@congty.vn"/></label></div><p className="survey-hint">Điền số điện thoại hoặc email. Thông tin và câu trả lời được lưu để người quản lý khảo sát của công ty tổng hợp; đây không phải khảo sát ẩn danh.</p>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary-button survey-start">Bắt đầu khảo sát →</button><p className="survey-privacy">Bằng việc bắt đầu, bạn đồng ý cung cấp thông tin trên cho mục đích khảo sát này.</p></form> : <form onSubmit={(e) => {
      e.preventDefault(); setError("");
      const missing = survey.questions.find((q) => q.required && (answers[q.id] === undefined || (Array.isArray(answers[q.id]) ? !(answers[q.id] as string[]).length : !String(answers[q.id]).trim())));
      if (missing) { setError(`Vui lòng trả lời: ${missing.title}`); document.getElementById(`q-${missing.id}`)?.scrollIntoView({ block: "center", behavior: "smooth" }); return; }
      startTransition(async () => { try { const result = await submitSurvey(token, submission, identity, answers, website); if (result.error) { setError(result.error); return; } setStep("done"); window.scrollTo({ top: 0, behavior: "instant" }); } catch { setError("Chưa gửi được phản hồi. Vui lòng thử lại; câu trả lời vẫn được giữ nguyên."); } });
    }}><fieldset disabled={pending} className="survey-editor-fields"><div className="survey-progress-card"><div><strong>Xin chào, {identity.full_name}</strong><button type="button" className="survey-text-button" onClick={() => { setStep("identity"); setError(""); }}>Sửa thông tin</button></div><progress value={answered} max={survey.questions.length}/><span>{answered}/{survey.questions.length} câu đã trả lời · Dấu * là bắt buộc</span></div>
      <label className="survey-honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={(e) => setWebsite(e.target.value)}/></label>
      {survey.questions.map((q, i) => <fieldset className="survey-public-card survey-public-question" id={`q-${q.id}`} key={q.id}><legend><span>Câu {i + 1}</span>{q.title}{q.required && <b aria-label="Bắt buộc"> *</b>}</legend>
        {q.type === "short" && <input aria-label={q.title} required={q.required} maxLength={500} value={String(answers[q.id] || "")} onChange={(e) => setAnswer(q.id, e.target.value)} placeholder="Câu trả lời của bạn…"/>}
        {q.type === "long" && <textarea aria-label={q.title} required={q.required} maxLength={5000} rows={4} value={String(answers[q.id] || "")} onChange={(e) => setAnswer(q.id, e.target.value)} placeholder="Chia sẻ ý kiến của bạn…"/>}
        {["single", "multiple"].includes(q.type) && <div className="survey-choice-list">{q.options.map((option) => <label className="survey-choice" key={option}><input type={q.type === "single" ? "radio" : "checkbox"} name={q.id} required={q.type === "single" && q.required} checked={q.type === "single" ? answers[q.id] === option : Array.isArray(answers[q.id]) && (answers[q.id] as string[]).includes(option)} onChange={(e) => { if (q.type === "single") setAnswer(q.id, option); else { const old = Array.isArray(answers[q.id]) ? answers[q.id] as string[] : []; setAnswer(q.id, e.target.checked ? [...old, option] : old.filter((v) => v !== option)); } }}/><span>{option}</span></label>)}</div>}
        {!q.required && q.type === "single" && <button type="button" className="survey-text-button" onClick={() => setAnswers((old) => { const next = { ...old }; delete next[q.id]; return next; })}>Bỏ lựa chọn</button>}
      </fieldset>)}
      {error && <p className="form-error survey-public-card" role="alert">{error}</p>}<div className="survey-public-card survey-submit"><p>Kiểm tra câu trả lời trước khi gửi. Bạn không thể chỉnh sửa sau khi đã gửi thành công.</p><button className="primary-button" type="submit">{pending ? "Đang gửi phản hồi…" : "Gửi khảo sát →"}</button></div>
    </fieldset></form>}
  </>;
}
